/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active jobs
         * @description Returns in-memory jobs tracked by the orchestrator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.Job"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream all job events via SSE
         * @description Establishes a Server-Sent Events (SSE) stream for real-time job updates.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by project slug */
                    project?: string;
                    /** @description Filter by website slug */
                    site?: string;
                    /** @description Filter by specific job ID */
                    job_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE Stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job details
         * @description Returns the current state of a background job.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job identifier */
                    jobID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.Job"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Cancel a job
         * @description Signals the orchestrator to stop a running job.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job identifier */
                    jobID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns all configured projects.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["registry.Project"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a project
         * @description Creates a named project that groups websites.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Project payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["server.CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["registry.Project"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Removes a project, its websites, and associated directory.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug or ID */
                    project: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List websites in a project
         * @description Retrieves websites scoped to a project slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["registry.Website"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a website inside a project
         * @description Registers a website origin scoped to the provided project slug.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                };
                cookie?: never;
            };
            /** @description Website payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["server.CreateWebsiteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["registry.Website"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a website
         * @description Removes a website and its associated directory.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/analyzer/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report analyzer capabilities for a site
         * @description Returns which analyzer backend a site is wired to (moku/burp/zap/…) and which optional ScanRequest fields it honors.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.AnalyzerCapabilitiesResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/analyzer/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check analyzer health for a site
         * @description Probes the analyzer backend's readiness. Returns 200 with a status string when reachable, 503 when unavailable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.AnalyzerHealthResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List website endpoints
         * @description Lists endpoints for the given project/site combination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by status */
                    status?: string;
                    /** @description Maximum results */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["indexer.Endpoint"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add website endpoints
         * @description Adds canonicalized URLs to the endpoint index for a website.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            /** @description Endpoint payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["server.AddWebsiteEndpointsRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.AddedEndpointsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/endpoints/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed endpoint information
         * @description Returns snapshot, scoring, diff, and security info for a canonical URL. Optionally compare specific versions.
         */
        get: {
            parameters: {
                query: {
                    /** @description Canonical URL */
                    url: string;
                    /** @description Base version ID for comparison */
                    base_version_id?: string;
                    /** @description Head version ID for comparison */
                    head_version_id?: string;
                };
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.EndpointDetails"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/jobs/enumerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an enumeration job
         * @description Launches URL discovery using configured enumerators. Each enumerator (spider, sitemap, robots, wayback) is enabled by including its config object.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            /** @description Enumeration configuration */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["server.StartEnumerateJobRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.Job"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/jobs/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a fetch job
         * @description Triggers a fetch of endpoints, optionally filtered by status/limit.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            /** @description Fetch options */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["server.StartFetchJobRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.Job"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/jobs/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a vulnerability scan job
         * @description Submits a URL for scanning via the configured analyzer backend (Moku native, Burp Suite, OWASP ZAP, etc.). Returns immediately with a job; poll /jobs/{jobID} or stream events to see results.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            /** @description Scan options */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["server.StartScanJobRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["app.Job"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/security/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get security diff overview for two versions
         * @description Returns security overview entries for all endpoints between base and head versions.
         */
        get: {
            parameters: {
                query: {
                    /** @description Base version ID (optional) */
                    base_version_id?: string;
                    /** @description Head version ID */
                    head_version_id: string;
                };
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["assessor.SecurityDiffOverview"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/websites/{site}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List versions for a website
         * @description Returns a list of versions (commits) for the website, ordered by most recent first.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of versions to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Project slug */
                    project: string;
                    /** @description Website slug */
                    site: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Version"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "analyzer.Backend": "moku" | "dast" | "nuclei" | "nikto" | "shodan" | "virustotal" | "zap";
        "analyzer.Capabilities": {
            /**
             * @description Async is true when SubmitScan returns before the scan has finished and
             *     GetScan must be polled. Every current backend sets this to true; the
             *     field exists for future adapters that may expose a synchronous API.
             */
            async?: boolean;
            /**
             * @description MaxConcurrentScans is the backend's self-reported concurrency ceiling.
             *     Zero means "unknown" or "unbounded"; callers should treat zero as "do
             *     not rate-limit based on this value".
             */
            max_concurrent_scans?: number;
            /**
             * @description SupportsAuth indicates whether the backend honors ScanRequest.Auth.
             *     When false, callers SHOULD NOT set Auth (it will be ignored).
             */
            supports_auth?: boolean;
            /**
             * @description SupportsScanProfile indicates whether the backend maps ScanRequest.Profile
             *     to a native scan configuration. When false, Profile is ignored and the
             *     backend's default profile is used.
             */
            supports_scan_profile?: boolean;
            /**
             * @description SupportsScope indicates whether the backend honors ScanRequest.Scope.
             *     When false, the scanner will scan whatever crawl strategy it default
             *     to without scope filtering.
             */
            supports_scope?: boolean;
            /**
             * @description Version is the backend's reported version string (e.g. "moku-0.1.0",
             *     "Burp Enterprise 2024.5", "ZAP 2.14.0"). Informational.
             */
            version?: string;
        };
        /** @enum {string} */
        "analyzer.Confidence": "tentative" | "firm" | "certain";
        "analyzer.Finding": {
            confidence?: components["schemas"]["analyzer.Confidence"];
            /**
             * @description CWE lists associated Common Weakness Enumeration IDs. Every major
             *     scanner reports these. Moku entries may be empty until the assessor
             *     rules are annotated with CWE mappings.
             */
            cwe?: number[];
            /** @description Description explains what the finding means in prose. */
            description?: string;
            /**
             * @description Evidence is a redacted request/response snippet or observation that
             *     demonstrates why the finding was raised.
             */
            evidence?: string;
            /**
             * @description ID is a backend-local stable identifier for this finding. Used by
             *     consumers to deduplicate results across poll iterations.
             */
            id?: string;
            /**
             * @description Method is the HTTP method associated with the finding when applicable
             *     (e.g. "POST" for a form-based injection point).
             */
            method?: string;
            /**
             * @description Parameter is the injection point name when the finding is parameter-
             *     scoped: a query parameter, form field, cookie, or header name.
             */
            parameter?: string;
            /**
             * @description Path is the path portion of the URL, surfaced separately for grouping
             *     findings by route in reporting UIs.
             */
            path?: string;
            /**
             * @description RawData carries backend-specific extras that do not fit the unified
             *     schema. Keys SHOULD be namespaced by backend (e.g. "burp.issue_type_id",
             *     "zap.messageId", "moku.contribution"). Consumers that read RawData are
             *     explicitly coupling themselves to a specific backend.
             */
            raw_data?: {
                [key: string]: unknown;
            };
            /**
             * @description References links to external documentation (OWASP, CVE, vendor
             *     advisories) describing the class of vulnerability.
             */
            references?: string[];
            /** @description Remediation is advice on how to fix the underlying weakness. */
            remediation?: string;
            severity?: components["schemas"]["analyzer.Severity"];
            /**
             * @description Title is a human-readable vulnerability name (e.g. "Reflected XSS",
             *     "Missing Content-Security-Policy header").
             */
            title?: string;
            /** @description URL is the full affected URL (scheme + host + path + query). */
            url?: string;
            /**
             * @description WASC lists associated WASC Threat Classification IDs. ZAP reports
             *     these natively; Burp and Moku usually leave this empty.
             */
            wasc?: number[];
        };
        "analyzer.ScanAuth": {
            /**
             * @description Extra holds scheme-specific parameters (e.g. form field selectors for
             *     Type=="form"). Keys and semantics are scanner-defined.
             */
            extra?: {
                [key: string]: string;
            };
            /**
             * @description Type selects the authentication scheme the scanner should use.
             *     Supported values: "none", "basic", "bearer", "form".
             */
            type?: string;
            username?: string;
        };
        /** @enum {string} */
        "analyzer.ScanProfile": "quick" | "balanced" | "thorough";
        "analyzer.ScanProgress": {
            note?: string;
            percent?: number;
            phase?: string;
        };
        "analyzer.ScanResult": {
            /**
             * @description Backend identifies which adapter produced this result, mirroring the
             *     value returned by Analyzer.Name().
             */
            backend?: components["schemas"]["analyzer.Backend"];
            completed_at?: string;
            /**
             * @description Error carries a human-readable failure message. Populated only when
             *     Status == StatusFailed.
             */
            error?: string;
            /**
             * @description Findings is the unified, backend-agnostic list of results. MUST be
             *     non-nil (possibly empty) once Status is StatusCompleted. This is what
             *     consumers read.
             */
            findings?: components["schemas"]["analyzer.Finding"][];
            /**
             * @description JobID is the backend-local scan identifier (Burp's task_id, ZAP's
             *     scan ID, Moku's UUID).
             */
            job_id?: string;
            /**
             * @description Progress is an optional mid-run progress snapshot. Backends MAY
             *     populate this while Status is StatusRunning. Consumers MUST tolerate
             *     a nil Progress at any status.
             */
            progress?: components["schemas"]["analyzer.ScanProgress"];
            /**
             * @description RawData is a backend-specific escape hatch. Keys MUST be namespaced
             *     by backend name (e.g. "burp.task_id", "zap.scan_id",
             *     "moku.exposure_score"). Reading RawData explicitly couples the caller
             *     to a specific backend and is NOT part of the LSP contract.
             */
            raw_data?: {
                [key: string]: unknown;
            };
            status?: components["schemas"]["analyzer.ScanStatus"];
            submitted_at?: string;
            /**
             * @description Summary aggregates per-severity counts. Mirrors Burp's issue_counts
             *     and ZAP's per-risk totals. MUST be non-nil once Status is
             *     StatusCompleted and its counts MUST sum to len(Findings).
             */
            summary?: components["schemas"]["analyzer.ScanSummary"];
            /** @description URL is the target that was scanned. */
            url?: string;
        };
        "analyzer.ScanScope": {
            exclude_hosts?: string[];
            exclude_paths?: string[];
            include_hosts?: string[];
            include_paths?: string[];
        };
        /** @enum {string} */
        "analyzer.ScanStatus": "pending" | "running" | "completed" | "failed" | "canceled";
        "analyzer.ScanSummary": {
            critical?: number;
            high?: number;
            info?: number;
            low?: number;
            medium?: number;
            total?: number;
        };
        /** @enum {string} */
        "analyzer.Severity": "info" | "low" | "medium" | "high" | "critical";
        "api.EnumerationConfig": {
            robots?: Record<string, never>;
            sitemap?: Record<string, never>;
            spider?: Record<string, never>;
            wayback?: Record<string, never>;
        };
        "api.FetchConfig": {
            /** @example 8 */
            concurrency?: number;
        };
        "app.EndpointDetails": {
            diff?: components["schemas"]["models.CombinedFileDiff"];
            score_result?: components["schemas"]["assessor.ScoreResult"];
            security_diff?: components["schemas"]["assessor.SecurityDiff"];
            snapshot?: components["schemas"]["models.Snapshot"];
        };
        "app.Job": {
            ended_at?: string;
            enumerated_urls?: string[];
            error?: string;
            id?: string;
            project?: string;
            /**
             * @description ScanResult is populated when Type == "scan" and the analyzer pipeline
             *     completed. It carries the unified industry-shaped Findings list.
             */
            scan_result?: components["schemas"]["analyzer.ScanResult"];
            security_overview?: components["schemas"]["assessor.SecurityDiffOverview"];
            started_at?: string;
            status?: components["schemas"]["app.JobStatus"];
            type?: string;
            website?: string;
        };
        /** @enum {string} */
        "app.JobStatus": "pending" | "running" | "done" | "failed" | "canceled";
        "assessor.EvidenceItem": {
            /**
             * @description Contribution is the numeric score contribution of this specific evidence item.
             *     Used to explain how each piece of evidence contributed to the overall score.
             */
            contribution?: number;
            /** @description Description is a short human-readable explanation of the evidence. */
            description?: string;
            /**
             * @description ID is an optional stable identifier for this evidence item in the ScoreResult.
             *     Useful for attribution rows to reference an evidence item unambiguously.
             */
            id?: string;
            /** @description Key is a short identifier for the evidence (e.g. "has-iframe", "suspicious-link"). */
            key?: string;
            /**
             * @description Locations holds zero or more structured locators where this evidence was observed.
             *     When non-empty it enables exact attribution and deterministic UI highlighting.
             */
            locations?: components["schemas"]["assessor.EvidenceLocation"][];
            /** @description RuleID identifies the rule that produced this evidence. */
            rule_id?: string;
            /** @description Severity is a human-level severity bucket such as "low", "medium", "high", "critical". */
            severity?: string;
            /** @description Value contains the raw value that triggered the evidence (string/number/map...). */
            value?: unknown;
        };
        "assessor.EvidenceLocation": {
            byte_end?: number;
            /**
             * @description Optional byte offsets into the file/body (start inclusive, end exclusive).
             *     Useful when the assessor is text-based rather than DOM-aware.
             */
            byte_start?: number;
            column?: number;
            /** @description For cookie-based evidence: the name of the cookie. */
            cookie_name?: string;
            dom_index?: number;
            /** @description Optional file path relative to the site working tree. */
            file_path?: string;
            /** @description For header-based evidence: the name of the header. */
            header_name?: string;
            /** @description Line and Column for precise text-based locations. */
            line?: number;
            line_end?: number;
            /** @description Optional line numbers (1-based). Useful for working-tree highlighting in the UI. */
            line_start?: number;
            /** @description Optional human note about this specific location (e.g., "in modal dialog"). */
            note?: string;
            param_name?: string;
            /** @description Dom Index is the 0-based index of the element in document.getElementsByTagName("*"). */
            parent_dom_index?: number;
            snapshot_id?: string;
            /**
             * @description Type describes what kind of location this is (e.g., "header", "cookie", "input", "form").
             *     Used by the UI to determine how to interpret and highlight the location.
             */
            type?: string;
            /** @description XPath expression (optional alternative to CSS selector). */
            xpath?: string;
        };
        "assessor.ScoreResult": {
            attack_surface?: components["schemas"]["attacksurface.AttackSurface"];
            /** @description Confidence is the assessor's confidence [0.0 .. 1.0] in this result. */
            confidence?: number;
            /** @description Evidence is the list of contributing evidence items. */
            evidence?: components["schemas"]["assessor.EvidenceItem"][];
            /** @description ExposureScore measures how much attack surface the page exposes [0..inf). */
            exposure_score?: number;
            /** @description HardeningScore measures how well security headers defend the page [0..1]. */
            hardening_score?: number;
            /** @description Meta contains any additional metadata about the scoring process. */
            meta?: {
                [key: string]: unknown;
            };
            /** @description Normalized is an integer normalized form [0 .. 100] for ease of reporting. */
            normalized?: number;
            /** @description Score combines exposure and hardening: exposure * (1 - hardening) [0..inf). */
            score?: number;
            /** @description SnapshotID is the snapshot this score applies to. */
            snapshot_id?: string;
            /** @description Timestamp is the time when this ScoreResult was produced. */
            timestamp?: string;
            /** @description Version identifies the scoring algorithm / heuristics version used. */
            version?: string;
            /** @description VersionID is the version this score applies to. */
            version_id?: string;
        };
        "assessor.SecurityDiff": {
            /** @description Attack surface deltas */
            attack_surface_changed?: boolean;
            attack_surface_changes?: components["schemas"]["attacksurface.AttackSurfaceChange"][];
            base_snapshot_id?: string;
            base_version_id?: string;
            /**
             * @description Per-axis score deltas. ExposureDelta is head.ExposureScore - base.ExposureScore
             *     (positive = more attack surface exposed). HardeningDelta is
             *     head.HardeningScore - base.HardeningScore (positive = better defenses).
             */
            exposure_delta?: number;
            hardening_delta?: number;
            head_snapshot_id?: string;
            head_version_id?: string;
            /** @description Score deltas */
            score_base?: number;
            score_delta?: number;
            score_head?: number;
            url?: string;
        };
        "assessor.SecurityDiffOverview": {
            base_version_id?: string;
            entries?: components["schemas"]["assessor.SecurityDiffOverviewEntry"][];
            head_version_id?: string;
        };
        "assessor.SecurityDiffOverviewEntry": {
            attack_surface_changed?: boolean;
            base_snapshot_id?: string;
            exposure_delta?: number;
            hardening_delta?: number;
            head_snapshot_id?: string;
            num_attack_surface_changes?: number;
            /** @description (scoreDelta > 0) for quick UI signals */
            regressed?: boolean;
            score_base?: number;
            score_delta?: number;
            score_head?: number;
            url?: string;
        };
        "attacksurface.AttackSurface": {
            collected_at?: string;
            content_type?: string;
            cookies?: components["schemas"]["attacksurface.CookieInfo"][];
            error_indicators?: string[];
            event_handlers?: components["schemas"]["attacksurface.EventHandlerInfo"][];
            forms?: components["schemas"]["attacksurface.Form"][];
            framework_hints?: string[];
            get_params?: components["schemas"]["attacksurface.Param"][];
            headers?: {
                [key: string]: string[];
            };
            post_params?: components["schemas"]["attacksurface.Param"][];
            scripts?: components["schemas"]["attacksurface.ScriptInfo"][];
            snapshot_id?: string;
            status_code?: number;
            url?: string;
        };
        "attacksurface.AttackSurfaceChange": {
            category?: components["schemas"]["attacksurface.ChangeCategory"];
            /** @description human-readable description of the change */
            detail?: string;
            evidence_locations?: components["schemas"]["attacksurface.EvidenceLocation"][];
            /** @description e.g., "form_added", "input_added", "header_changed", "cookie_changed", "script_added" */
            kind?: string;
            score?: number;
        };
        /** @enum {string} */
        "attacksurface.ChangeCategory": "upload_surface" | "auth_surface" | "admin_surface" | "security_regression" | "cookie_risk" | "cookie_regression" | "form_surface" | "input_surface" | "script_surface" | "param_surface" | "generic";
        "attacksurface.CookieInfo": {
            domain?: string;
            http_only?: boolean;
            name?: string;
            path?: string;
            same_site?: string;
            secure?: boolean;
        };
        "attacksurface.EventHandlerInfo": {
            element_selector?: string;
            /** @description e.g. "click", "submit" */
            event_type?: string;
        };
        "attacksurface.EvidenceLocation": {
            cookie_name?: string;
            /** @description index into getElementsByTagName for this Type */
            dom_index?: number;
            header_name?: string;
            param_name?: string;
            /** @description index of parent form for inputs */
            parent_dom_index?: number;
            snapshot_id?: string;
            /** @description "form","input","header","cookie","script",... */
            type?: string;
        };
        "attacksurface.Form": {
            action?: string;
            dom_classes?: string[];
            dom_id?: string;
            /**
             * @description Location hints
             *     0-based index into formElement.getElementsByTagName("form")
             */
            dom_index?: number;
            inputs?: components["schemas"]["attacksurface.FormInput"][];
            method?: string;
        };
        "attacksurface.FormInput": {
            dom_classes?: string[];
            dom_id?: string;
            /**
             * @description Location hints
             *     0-based index into formElement.getElementsByTagName("input")
             */
            dom_index?: number;
            name?: string;
            required?: boolean;
            type?: string;
        };
        "attacksurface.Param": {
            name?: string;
            /** @description "query", "body", "form" */
            origin?: string;
        };
        "attacksurface.ScriptInfo": {
            /**
             * @description Location hints
             *     0-based index into document.getElementsByTagName("script")
             */
            dom_index?: number;
            inline?: boolean;
            src?: string;
        };
        "indexer.Endpoint": {
            canonical_url?: string;
            first_discovered_at?: number;
            host?: string;
            id?: string;
            last_discovered_at?: number;
            last_fetched_at?: number;
            last_fetched_version?: string;
            meta?: string;
            path?: string;
            source?: string;
            status?: string;
            url?: string;
        };
        "models.BodyDiff": {
            base_id?: string;
            chunks?: components["schemas"]["models.DiffChunk"][];
            head_id?: string;
        };
        "models.Change": {
            from?: string[];
            to?: string[];
        };
        "models.CombinedFileDiff": {
            body_diff?: components["schemas"]["models.BodyDiff"];
            file_path?: string;
            headers_diff?: components["schemas"]["models.HeaderDiff"];
        };
        "models.DiffChunk": {
            base_len?: number;
            base_start?: number;
            /** @description content for added/modified chunks */
            content?: string;
            head_len?: number;
            head_start?: number;
            /** @description optional DOM selector or descriptor */
            path?: string;
            /** @description e.g., "added", "removed", "modified" */
            type?: string;
        };
        "models.HeaderDiff": {
            added?: {
                [key: string]: string[];
            };
            changed?: {
                [key: string]: components["schemas"]["models.Change"];
            };
            redacted?: string[];
            removed?: {
                [key: string]: string[];
            };
        };
        "models.Snapshot": {
            /** @description Body contains the raw HTML bytes for the snapshot. */
            body?: number[];
            /** @description CreatedAt is the capture timestamp (if known). */
            created_at?: string;
            /** @description Headers contains optional header data (headers, content-type, etc). */
            headers?: {
                [key: string]: string[];
            };
            /** @description ID is an opaque identifier (e.g., uuid or incremental string) assigned by the tracker. */
            id?: string;
            /** @description Status Code indicates the result of the snapshot attempt (e.g., 200, 404, error codes). */
            status_code?: number;
            /** @description URL is the source URL for the snapshot when available. */
            url?: string;
            /** @description VersionID is the version this snapshot belongs to. */
            version_id?: string;
        };
        "models.Version": {
            /** @description Author is optional metadata about who committed. */
            author?: string;
            /** @description ID is the version identifier (string). */
            id?: string;
            /** @description Message is the commit message. */
            message?: string;
            /** @description Parent is the parent version ID (empty if none). */
            parent?: string;
            /** @description Timestamp is the commit time. */
            timestamp?: string;
        };
        "registry.Project": {
            created_at?: number;
            description?: string;
            id?: string;
            meta?: string;
            name?: string;
            slug?: string;
        };
        "registry.Website": {
            config?: string;
            created_at?: number;
            id?: string;
            last_seen_at?: number;
            origin?: string;
            project_id?: string;
            slug?: string;
            storage_path?: string;
        };
        "server.AddWebsiteEndpointsRequest": {
            /** @example manual */
            source?: string;
            /**
             * @example [
             *       "[\"http://localhost:9999/index\"]"
             *     ]
             */
            urls?: string[];
        };
        "server.AddedEndpointsResponse": {
            /** @example 42 */
            added?: number;
        };
        "server.AnalyzerCapabilitiesResponse": {
            backend?: components["schemas"]["analyzer.Backend"];
            capabilities?: components["schemas"]["analyzer.Capabilities"];
        };
        "server.AnalyzerHealthResponse": {
            backend?: components["schemas"]["analyzer.Backend"];
            /** @example ok */
            status?: string;
        };
        "server.CreateProjectRequest": {
            /** @example Project for IBM's public website */
            description?: string;
            /** @example IBM */
            name?: string;
            /** @example ibm */
            slug?: string;
        };
        "server.CreateWebsiteRequest": {
            /** @example http://localhost:9999 */
            origin?: string;
            /** @example demo */
            slug?: string;
        };
        "server.ErrorResponse": {
            /** @example not found */
            error?: string;
        };
        "server.StartEnumerateJobRequest": {
            config?: components["schemas"]["api.EnumerationConfig"];
        };
        "server.StartFetchJobRequest": {
            config?: components["schemas"]["api.FetchConfig"];
            /** @example 100 */
            limit?: number;
            /** @description Filter overrides for this fetch job */
            skip_extensions?: string[];
            skip_patterns?: string[];
            skip_status_codes?: number[];
            /**
             * @default *
             * @example *
             */
            status: string;
        };
        "server.StartScanJobRequest": {
            auth?: components["schemas"]["analyzer.ScanAuth"];
            /** @example 300000000000 */
            max_duration?: number;
            /** @example balanced */
            profile?: components["schemas"]["analyzer.ScanProfile"];
            raw_options?: {
                [key: string]: string;
            };
            scope?: components["schemas"]["analyzer.ScanScope"];
            /** @example https://example.com/ */
            url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
